apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kogito2
  name: kogito2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kogito2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kogito2
    spec:
      containers:
      - image: 747subhasish/kogito-app2
        name: kogito-app2
        resources: {}
status: {}
