apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kogito2
  name: kogito2
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kogito2
status:
  loadBalancer: {}
